[opener]
edit = [
	{ run = 'zellij-open "$@"', block = true, for = "unix" }
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "application/json", use = "edit" },
	{ name = "*.md", use = "edit" }
]

[mgr]
ratio = [0, 1, 0]
show_hidden = true
